apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    app.belongs.to: AdvancedAnalytic
data:
  kubeprojectname: {{ .Release.Namespace | quote }}
  appname: {{ .Values.appname }}